### ISSUE TITLE
Typo in repo description: "food pedal"

### ISSUE THREAD

**Issue by pmeinhardt** [tessi/programming_paddle#2]
"Stole my wifes sewing machine food pedal. Using it for programming now. "

I think you meant to type: "wife's" and "foot pedal" :wink: :nerd_face: 

Anyway: This is awesome and thanks for open-sourcing! :metal:

**Comment by tessi** [comment]
🌯 🍎 🍌 👣 

Thanks for noticing and telling me :) fixed the typo
